### PR TITLE
Feature/menu bar

### LINKED ISSUE #17: Navbar Design
**Navbar Design**
Adding Navbar.

**__Technical Considerations__**
Design Navbar UI Component. 
Add Search section UI
Add menu items UI

**__Menu Items__**
Login link and Profile Image

### PR DESCRIPTION
**Pull request by Markotweyo**

### CODE REVIEW

**Review by themythia — COMMENTED** [review]
It has minor problems: 
- Height seems off due to `calc(100%-48px)`
- Library icon/text color seems wrong (you can use the variables in `index.css`)

**Comment by themythia** [comment]
- Added basic routing to navbar
- Added desktop version of navbar
- Added dark mode for navbar

**Comment by ScarSymmetry** [comment]
wideicons
Everything is cool , just maybe the icons between tablet and desktop breakpoints are too wide apart , but thats just for my taste

**Review by ScarSymmetry — APPROVED** [review]

**Comment by themythia** [comment]
>  Everything is cool , just maybe the icons between tablet and desktop breakpoints are too wide apart , but thats just for my taste

Brought them a bit closer with 39e3ad0

**Pull request merged**
